/* Generated By:JavaCC: Do not edit this line. HorarioLeitorConstants.java */
package horario.leitor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HorarioLeitorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SALA = 1;
  /** RegularExpression Id. */
  int SPACE = 2;
  /** RegularExpression Id. */
  int DIA = 3;
  /** RegularExpression Id. */
  int T2PNT = 4;
  /** RegularExpression Id. */
  int T1NUM = 5;
  /** RegularExpression Id. */
  int T2NUM = 6;
  /** RegularExpression Id. */
  int CADEIRA = 7;
  /** RegularExpression Id. */
  int NOME1 = 8;
  /** RegularExpression Id. */
  int NOME2 = 9;
  /** RegularExpression Id. */
  int TIPO = 10;
  /** RegularExpression Id. */
  int TURNO = 11;
  /** RegularExpression Id. */
  int TURMA = 12;
  /** RegularExpression Id. */
  int NUM = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SALA>",
    "<SPACE>",
    "<DIA>",
    "\":\"",
    "<T1NUM>",
    "<T2NUM>",
    "<CADEIRA>",
    "<NOME1>",
    "<NOME2>",
    "<TIPO>",
    "<TURNO>",
    "<TURMA>",
    "<NUM>",
  };

}
